name: Continuous Integration

on:
  push:
    paths:
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile project
        run: mvn compile
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$HOME/.m2/repository'

      - name: Build Docker images with Jib
        run: mvn compile jib:dockerBuild
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$HOME/.m2/repository'

      - name: Build Docker images with Jib
        run: mvn jib:dockerBuild
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$HOME/.m2/repository'

      - name: Stop and Start Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
