on:
  push:
    paths:
      - '**/pom.xml'
      - '**/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker images with Jib
        run: mvn clean compile jib:build

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Watch for file changes
        run: |
          while true; do
            # Monitor for changes in pom.xml and src directory
            if git diff --quiet HEAD^ HEAD -- '**/pom.xml' '**/src/'; then
              echo "No changes detected. Sleeping for 10 seconds..."
              sleep 10
            else
              echo "Changes detected. Restarting Docker Compose..."
              docker-compose down
              docker-compose up -d
            fi
          done
